import type { SimulationScenarioDefinition, SimulationScenarioKey } from '../types/simulation'

const harborCenter = { lat: 37.8078, lon: -122.3749 }

export const scenarioDefinitions: Record<SimulationScenarioKey, SimulationScenarioDefinition> = {
  harborIntrusion: {
    key: 'harborIntrusion',
    label: 'Harbor intrusion',
    seed: 'smoken-mirrors-harbor-v1',
    missionArea: 'MissionArea-Harbor-North',
    startTimestamp: '2026-05-02T17:41:00.000Z',
    center: harborCenter,
    heroTrackId: 'TRK-SM-001',
    durationSeconds: 900,
    objective: 'Protect waterfront assets and maintain custody on suspicious inbound tracks.',
    phases: [
      {
        id: 'initial-detection',
        label: 'Initial detection',
        startSecond: 0,
        description: 'Radar seeds an unknown low-profile track southwest of the protected waterfront.',
        nextEvent: 'Correlate passive acoustic/RF bearings',
      },
      {
        id: 'multi-sensor-correlation',
        label: 'Multi-sensor correlation',
        startSecond: 18,
        description: 'Radar, acoustic, and RF bearings begin converging on one fused candidate.',
        nextEvent: 'Establish fused custody',
      },
      {
        id: 'fused-track-established',
        label: 'Fused track established',
        startSecond: 42,
        description: 'The fusion engine promotes the candidate to a maintained high-interest fused track.',
        nextEvent: 'Task EO/IR confirmation',
      },
      {
        id: 'eo-tasked',
        label: 'EO camera tasked',
        startSecond: 64,
        description: 'EO/IR is slewed to the predicted intercept corridor for visual custody.',
        nextEvent: 'Assess threat trend',
      },
      {
        id: 'threat-increasing',
        label: 'Threat increasing',
        startSecond: 92,
        description: 'The track closes range to the restricted waterfront and threat scoring rises.',
        nextEvent: 'Prompt operator review',
      },
      {
        id: 'operator-review',
        label: 'Operator review',
        startSecond: 126,
        description: 'The operator queue prioritizes the track for confirm, monitor, or dispatch.',
        nextEvent: 'Recommend response action',
      },
      {
        id: 'action-recommended',
        label: 'Action recommended',
        startSecond: 166,
        description: 'Fusion recommends maintaining custody and preparing harbor intercept response.',
        nextEvent: 'Monitor response / resolution',
      },
      {
        id: 'response-resolution',
        label: 'Response / resolution',
        startSecond: 220,
        description: 'The track remains under fused custody while response actions are tracked.',
        nextEvent: 'Continue mission watch',
      },
    ],
    platforms: [
      {
        id: 'PLAT-HARBOR-01',
        callsign: 'Harbor Watch',
        platformType: 'FIXED_RADAR_EO',
        ownerUnit: 'Blue Cell',
        lat: 37.8107,
        lon: -122.3786,
      },
      {
        id: 'PLAT-PIER-03',
        callsign: 'Pier Scout',
        platformType: 'MOBILE_RF_TRIPOD',
        ownerUnit: 'Blue Cell',
        lat: 37.8069,
        lon: -122.3924,
      },
      {
        id: 'PLAT-BUOY-07',
        callsign: 'Buoy Seven',
        platformType: 'SMART_ACOUSTIC_BUOY',
        ownerUnit: 'Maritime Ops',
        lat: 37.8029,
        lon: -122.3679,
      },
      {
        id: 'PLAT-CRANE-02',
        callsign: 'Crane EO',
        platformType: 'FIXED_EO_IR',
        ownerUnit: 'Port Authority',
        lat: 37.8145,
        lon: -122.3628,
      },
    ],
    sensors: [
      {
        id: 'SENS-RDR-21',
        platformId: 'PLAT-HARBOR-01',
        modality: 'RADAR',
        measurementKind: 'RADAR_GMTI',
        rangeMaxM: 5200,
        fovType: 'SECTOR',
        fovHDeg: 94,
        latencyMsP50: 84,
        cadenceSeconds: 2,
        reliability: 0.88,
        confidenceMean: 0.68,
        confidenceJitter: 0.11,
        bearingNoiseDeg: 2.2,
        rangeNoiseM: 38,
      },
      {
        id: 'SENS-RF-14',
        platformId: 'PLAT-PIER-03',
        modality: 'RF',
        measurementKind: 'RF_ESM',
        rangeMaxM: 3600,
        fovType: 'OMNIDIRECTIONAL',
        fovHDeg: 360,
        latencyMsP50: 126,
        cadenceSeconds: 3,
        reliability: 0.72,
        confidenceMean: 0.64,
        confidenceJitter: 0.16,
        bearingNoiseDeg: 5.8,
        rangeNoiseM: 130,
      },
      {
        id: 'SENS-AC-09',
        platformId: 'PLAT-BUOY-07',
        modality: 'ACOUSTIC',
        measurementKind: 'ACOUSTIC_TONAL',
        rangeMaxM: 1800,
        fovType: 'OMNIDIRECTIONAL',
        fovHDeg: 360,
        latencyMsP50: 340,
        cadenceSeconds: 4,
        reliability: 0.64,
        confidenceMean: 0.58,
        confidenceJitter: 0.17,
        bearingNoiseDeg: 9,
        rangeNoiseM: 180,
      },
      {
        id: 'SENS-EO-03',
        platformId: 'PLAT-CRANE-02',
        modality: 'EO',
        measurementKind: 'EO_NIR',
        rangeMaxM: 2600,
        fovType: 'GIMBALED',
        fovHDeg: 28,
        latencyMsP50: 210,
        cadenceSeconds: 5,
        reliability: 0.58,
        confidenceMean: 0.7,
        confidenceJitter: 0.14,
        bearingNoiseDeg: 1.5,
        rangeNoiseM: 24,
        degradationWindows: [
          {
            startSecond: 0,
            endSecond: 58,
            reliabilityMultiplier: 0.08,
            confidenceOffset: -0.24,
            reason: 'EO camera awaiting slew tasking',
          },
          {
            startSecond: 84,
            endSecond: 120,
            reliabilityMultiplier: 0.25,
            confidenceOffset: -0.18,
            reason: 'EO line of sight masked by crane structure',
          },
        ],
      },
      {
        id: 'SENS-IR-08',
        platformId: 'PLAT-CRANE-02',
        modality: 'IR',
        measurementKind: 'IR_MWIR',
        rangeMaxM: 2300,
        fovType: 'GIMBALED',
        fovHDeg: 22,
        latencyMsP50: 185,
        cadenceSeconds: 6,
        reliability: 0.54,
        confidenceMean: 0.67,
        confidenceJitter: 0.13,
        bearingNoiseDeg: 1.7,
        rangeNoiseM: 30,
        degradationWindows: [
          {
            startSecond: 0,
            endSecond: 68,
            reliabilityMultiplier: 0.16,
            confidenceOffset: -0.16,
            reason: 'IR cue below tasking threshold',
          },
        ],
      },
    ],
    protectedAssets: [
      {
        id: 'ASSET-WATERFRONT',
        label: 'Protected Waterfront',
        priority: 'critical',
        lat: 37.8095,
        lon: -122.3697,
      },
    ],
    protectedZones: [
      {
        id: 'ZONE-HARBOR-MISSION',
        label: 'Harbor North Mission Box',
        kind: 'mission',
        points: [
          { lat: 37.7939, lon: -122.3982 },
          { lat: 37.8225, lon: -122.3974 },
          { lat: 37.8239, lon: -122.3545 },
          { lat: 37.7949, lon: -122.3506 },
          { lat: 37.7939, lon: -122.3982 },
        ],
      },
      {
        id: 'ZONE-HARBOR-RESTRICTED',
        label: 'Restricted Waterfront Standoff',
        kind: 'restricted',
        points: [
          { lat: 37.8057, lon: -122.3748 },
          { lat: 37.8136, lon: -122.374 },
          { lat: 37.8142, lon: -122.3654 },
          { lat: 37.8063, lon: -122.3639 },
          { lat: 37.8057, lon: -122.3748 },
        ],
      },
    ],
  },
  falsePositiveClutter: {
    key: 'falsePositiveClutter',
    label: 'False-positive clutter',
    seed: 'smoken-mirrors-clutter-v1',
    missionArea: 'MissionArea-Harbor-North',
    startTimestamp: '2026-05-02T18:05:00.000Z',
    center: harborCenter,
    heroTrackId: 'TRK-FP-001',
    durationSeconds: 720,
    objective: 'Reduce false positives without losing custody on real threats.',
    phases: [
      {
        id: 'initial-detection',
        label: 'Initial detection',
        startSecond: 0,
        description: 'Several low-confidence radar returns appear near harbor clutter.',
        nextEvent: 'Check for independent sensor support',
      },
      {
        id: 'multi-sensor-correlation',
        label: 'Weak correlation',
        startSecond: 20,
        description: 'Passive sensors do not corroborate most low-confidence returns.',
        nextEvent: 'Downgrade likely biological tracks',
      },
      {
        id: 'fused-track-established',
        label: 'Clutter review',
        startSecond: 48,
        description: 'The queue holds bird-like tracks for review while confidence decays.',
        nextEvent: 'Recommend monitor or clear',
      },
      {
        id: 'threat-increasing',
        label: 'Threat stable',
        startSecond: 82,
        description: 'No track shows persistent approach behavior toward the protected asset.',
        nextEvent: 'Clear false positives',
      },
      {
        id: 'operator-review',
        label: 'Operator review',
        startSecond: 118,
        description: 'Low-risk contacts are monitored and downgraded as stale evidence accumulates.',
        nextEvent: 'Resolve clutter',
      },
      {
        id: 'response-resolution',
        label: 'Resolved clutter',
        startSecond: 168,
        description: 'False-positive tracks are cleared or left in passive watch status.',
        nextEvent: 'Continue mission watch',
      },
    ],
    platforms: [],
    sensors: [],
    protectedAssets: [],
    protectedZones: [],
  },
  intermittentCustody: {
    key: 'intermittentCustody',
    label: 'Reacquire / intermittent custody',
    seed: 'smoken-mirrors-reacquire-v1',
    missionArea: 'MissionArea-Harbor-North',
    startTimestamp: '2026-05-02T18:32:00.000Z',
    center: harborCenter,
    heroTrackId: 'TRK-IC-001',
    durationSeconds: 780,
    objective: 'Maintain custody through sensor dropout and recover the fused track.',
    phases: [
      {
        id: 'initial-detection',
        label: 'Initial detection',
        startSecond: 0,
        description: 'A low-altitude UAV candidate is detected near marina clutter.',
        nextEvent: 'Build multi-sensor custody',
      },
      {
        id: 'multi-sensor-correlation',
        label: 'Custody maintained',
        startSecond: 20,
        description: 'Radar and RF maintain the track while EO attempts visual confirmation.',
        nextEvent: 'Watch for sensor dropout',
      },
      {
        id: 'custody-drop',
        label: 'Sensor dropout',
        startSecond: 62,
        description: 'Radar becomes degraded by multipath and EO remains masked.',
        nextEvent: 'Reacquire via passive sensors',
      },
      {
        id: 'reacquiring',
        label: 'Reacquiring',
        startSecond: 92,
        description: 'The fusion engine holds tentative custody while stale detections decay.',
        nextEvent: 'Recover fused custody',
      },
      {
        id: 'fused-track-established',
        label: 'Track reacquired',
        startSecond: 124,
        description: 'RF and thermal cues recover the track and custody returns to maintained.',
        nextEvent: 'Update recommended action',
      },
      {
        id: 'operator-review',
        label: 'Operator review',
        startSecond: 160,
        description: 'The operator is prompted to monitor the recovered track and keep EO/IR tasked.',
        nextEvent: 'Continue mission watch',
      },
    ],
    platforms: [],
    sensors: [],
    protectedAssets: [],
    protectedZones: [],
  },
}

scenarioDefinitions.falsePositiveClutter.platforms = scenarioDefinitions.harborIntrusion.platforms
scenarioDefinitions.falsePositiveClutter.sensors = scenarioDefinitions.harborIntrusion.sensors.map((sensor) => ({
  ...sensor,
  reliability: sensor.modality === 'RADAR' ? Math.min(0.92, sensor.reliability + 0.08) : sensor.reliability * 0.72,
  confidenceMean: sensor.modality === 'RADAR' ? sensor.confidenceMean - 0.08 : sensor.confidenceMean - 0.04,
}))
scenarioDefinitions.falsePositiveClutter.protectedAssets = scenarioDefinitions.harborIntrusion.protectedAssets
scenarioDefinitions.falsePositiveClutter.protectedZones = scenarioDefinitions.harborIntrusion.protectedZones

scenarioDefinitions.intermittentCustody.platforms = scenarioDefinitions.harborIntrusion.platforms
scenarioDefinitions.intermittentCustody.sensors = scenarioDefinitions.harborIntrusion.sensors.map((sensor) => ({
  ...sensor,
  degradationWindows:
    sensor.modality === 'RADAR'
      ? [
          {
            startSecond: 62,
            endSecond: 108,
            reliabilityMultiplier: 0.18,
            confidenceOffset: -0.22,
            reason: 'Radar multipath against marina clutter',
          },
        ]
      : sensor.modality === 'EO'
        ? [
            {
              startSecond: 28,
              endSecond: 74,
              reliabilityMultiplier: 0.2,
              confidenceOffset: -0.18,
              reason: 'EO target masked by background lighting',
            },
          ]
        : sensor.degradationWindows,
}))
scenarioDefinitions.intermittentCustody.protectedAssets = scenarioDefinitions.harborIntrusion.protectedAssets
scenarioDefinitions.intermittentCustody.protectedZones = scenarioDefinitions.harborIntrusion.protectedZones

export const scenarioOptions = Object.values(scenarioDefinitions).map((scenario) => ({
  key: scenario.key,
  label: scenario.label,
}))
